name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '8.0/**'
      - '11.0/**'
      - '17.0/**'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-20.04]

    strategy:
      fail-fast: false
      matrix:
        version: [8.0, 11.0]
        include:
          - version: 8.0
            docker-context: 8.0/jdk/debian/default
            docker-tags: |
              nicoherbigde/adoptopenjdk-openjdk:8
              nicoherbigio/adoptopenjdk-openjdk:8
              nicoherbigde/adoptopenjdk-openjdk:8.0
              nicoherbigio/adoptopenjdk-openjdk:8.0
              nicoherbigde/adoptopenjdk-openjdk:8.0.352
              nicoherbigio/adoptopenjdk-openjdk:8.0.352
          - version: 11.0
            docker-context: 11.0/jdk/debian/default
            docker-tags: |
              nicoherbigde/adoptopenjdk-openjdk:11
              nicoherbigio/adoptopenjdk-openjdk:11
              nicoherbigde/adoptopenjdk-openjdk:11.0
              nicoherbigio/adoptopenjdk-openjdk:11.0
              nicoherbigde/adoptopenjdk-openjdk:11.0.17
              nicoherbigio/adoptopenjdk-openjdk:11.0.17
          - version: 17.0
            docker-context: 17.0/jdk/debian/default
            docker-tags: |
              nicoherbigde/adoptopenjdk-openjdk:17
              nicoherbigio/adoptopenjdk-openjdk:17
              nicoherbigde/adoptopenjdk-openjdk:17.0
              nicoherbigio/adoptopenjdk-openjdk:17.0
              nicoherbigde/adoptopenjdk-openjdk:17.0.5
              nicoherbigio/adoptopenjdk-openjdk:17.0.5

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and Push it to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          push: true
          tags: ${{ matrix.docker-tags }}
